### ISSUE TITLE
[REQUEST] Toggle to Exclude Wizard Towers

### ISSUE THREAD

**Issue by Lime7242** [drblaui/cookie-clicker-autobuy#32]
**Is your feature request related to a problem? Please describe.**
This mod makes it very hard to do golden cookie combos, I can't sell wizard towers to cast multiple spells.
I know I can turn the autobuy to 0, but that takes a while, and you have to be fast to pull off good cookie combos.

**Describe the solution you'd like**
Add a button in the mod settings that excludes wizard towers from the autobuy, so the mod stops buying towers

**Comment by drblaui** [comment]
This should be implemented now and updated on Steam. Thanks for the suggestion! :)
